
project_id = "orhtixtxklzhaqryeirk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[function]]
name = "chat-with-ai"
verify_jwt = true

[[function]]
name = "process-payment"
verify_jwt = true

[[function]]
name = "process-rank-analysis"
verify_jwt = false
