// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orhtixtxklzhaqryeirk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yaHRpeHR4a2x6aGFxcnllaXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNDA1NzEsImV4cCI6MjA1NDgxNjU3MX0.irk8YFPkqhYsG2SBtWhC2ogecYmzhI98p3AYIgzjZpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);